"""
services/confidence_service.py

Combines raw signal scores from DetectionService into a single confidence
score, assigns a classification tier, and returns the exact transparency
label text.

Weighting (from planning.md):
  LLM score         × 0.65  — reasons about meaning; more reliable across genres
  Stylometric score × 0.35  — surface statistics; fast but genre-sensitive

Thresholds (from planning.md):
  score < 0.40      → "high_confidence_human"
  0.40 ≤ score < 0.70 → "uncertain"
  score ≥ 0.70      → "high_confidence_ai"

The 0.70 floor for the AI label implements the asymmetry principle:
a false positive (human text labelled AI) harms a creator's reputation more
than a false negative. We require strong signal agreement before applying
the most consequential label.
"""

# ---------------------------------------------------------------------------
# Threshold constants
# ---------------------------------------------------------------------------

_AI_THRESHOLD    = 0.70   # score ≥ this → high_confidence_ai
_HUMAN_THRESHOLD = 0.40   # score < this → high_confidence_human
# between the two → uncertain

# ---------------------------------------------------------------------------
# Exact transparency label text — Milestone 5 specification
#
# Rules enforced by this file:
#   • Plain language — no jargon like "classifier output" or "logit score"
#   • Wording visibly differs between tiers (not just a different number)
#   • A non-technical reader can understand each label without extra context
# ---------------------------------------------------------------------------

_LABEL_TEXT = {
    "high_confidence_ai": (
        "This content was likely generated by an AI writing tool. Our system "
        "analyzed the writing style and found patterns strongly associated with "
        "AI-generated text. If you wrote this yourself, you can file an appeal below."
    ),
    "uncertain": (
        "Our system could not confidently determine whether this content was "
        "written by a human or generated by AI. The writing contains a mix of "
        "signals. The author may wish to provide additional context."
    ),
    "high_confidence_human": (
        "This content appears to have been written by a human. Our system found "
        "strong markers of personal voice, stylistic variation, and natural "
        "writing patterns."
    ),
}

# Map tier → short classification string used elsewhere in the codebase
_TIER_TO_CLASSIFICATION = {
    "high_confidence_ai":    "ai",
    "uncertain":             "uncertain",
    "high_confidence_human": "human",
}

# Signal weights — must sum to 1.0
_LLM_WEIGHT         = 0.65
_STYLOMETRIC_WEIGHT = 0.35


# ---------------------------------------------------------------------------
# Standalone helper — can be imported and called without instantiating the class
# ---------------------------------------------------------------------------

def assign_label(score: float) -> dict:
    """
    Map a confidence score to a transparency label dict.

    Args:
        score: Combined confidence score in [0.0, 1.0].
               Higher values indicate AI authorship.

    Returns:
        {
            "tier":         str,  # "high_confidence_ai" | "uncertain" |
                                  #  "high_confidence_human"
            "display_text": str,  # plain-language label shown to users
        }
    """
    if score >= _AI_THRESHOLD:
        tier = "high_confidence_ai"
    elif score >= _HUMAN_THRESHOLD:
        tier = "uncertain"
    else:
        tier = "high_confidence_human"

    return {
        "tier":         tier,
        "display_text": _LABEL_TEXT[tier],
    }


# ---------------------------------------------------------------------------
# Service class
# ---------------------------------------------------------------------------

class ConfidenceService:
    """
    Produces the final analysis result from two raw signal dictionaries.

    Usage:
        svc = ConfidenceService()
        result = svc.combine(llm_result, stylometric_result)
    """

    def combine(self, llm_result: dict, stylometric_result: dict) -> dict:
        """
        Weighted average of two signals → classification + label.

        Args:
            llm_result:          Output of DetectionService.run_llm_signal().
            stylometric_result:  Output of DetectionService.run_stylometric_signal().

        Returns:
            {
                "classification":    str,   # "ai" | "human" | "uncertain"
                "label_tier":        str,   # "high_confidence_ai" | ...
                "confidence":        float, # combined score 0.0–1.0
                "label":             str,   # plain-language display text
                "signals": {
                    "llm_score":          float,
                    "stylometric_score":  float,
                    "llm_detail":         dict,
                    "stylometric_detail": dict,
                }
            }
        """
        llm_score         = float(llm_result.get("score", 0.5))
        stylometric_score = float(stylometric_result.get("score", 0.5))

        # Core combination formula — weights defined as module constants
        combined = (llm_score * _LLM_WEIGHT) + (stylometric_score * _STYLOMETRIC_WEIGHT)
        combined = round(combined, 4)

        label_info     = assign_label(combined)
        tier           = label_info["tier"]
        classification = _TIER_TO_CLASSIFICATION[tier]

        return {
            "classification":   classification,
            "label_tier":       tier,
            "confidence":       combined,
            "label":            label_info["display_text"],
            "signals": {
                "llm_score":          round(llm_score, 4),
                "stylometric_score":  round(stylometric_score, 4),
                "llm_detail":         llm_result,
                "stylometric_detail": stylometric_result,
            },
        }
