"""
services/detection_service.py

Runs the two independent detection signals against submitted text.

Responsibility: produce raw signal dictionaries.
Combination and labelling is handled by ConfidenceService.

Signal 1 — Groq LLM Classification
    Calls the Groq chat-completion API with llama-3.3-70b-versatile.
    Asks the model to classify the text and return structured JSON.
    Score: 0.0 (human) → 1.0 (AI).

Signal 2 — Stylometric Heuristics
    Pure Python computation of four measurable text properties:
      • Sentence length variance
      • Average sentence length  (informational; not in combined score)
      • Type-token ratio
      • Punctuation density
    Score: 0.0 (human) → 1.0 (AI).

Neither signal is definitive on its own. ConfidenceService combines them.
"""

import json
import math
import re
import string

from groq import Groq


# ---------------------------------------------------------------------------
# LLM signal constants
# ---------------------------------------------------------------------------

_MODEL = "llama-3.3-70b-versatile"

# Keep temperature low so the model is consistent across repeated calls.
_TEMPERATURE = 0.1

# Hard timeout in seconds — Groq is fast, 20 s is generous.
_TIMEOUT = 20.0

# The prompt instructs the model to respond ONLY with a JSON object.
# response_format={"type": "json_object"} enforces this at the API level,
# but the prompt instruction is a second layer of defense.
_SYSTEM_PROMPT = """\
You are an expert text analyst. Your task is to determine whether the \
provided text was written by a human or generated by an AI writing tool.

Analyze the writing style, sentence structure, vocabulary, and coherence \
patterns. Then classify the text as one of:
  - "likely_human"  : strong evidence of human authorship
  - "likely_ai"     : strong evidence of AI generation
  - "uncertain"     : insufficient evidence to decide confidently

Respond ONLY with a JSON object — no markdown, no explanation outside the \
JSON. Use exactly this structure:

{
  "classification": "likely_human" | "likely_ai" | "uncertain",
  "confidence": <float between 0.0 and 1.0>,
  "reasoning": "<one or two plain-language sentences explaining your judgment>"
}

Where "confidence" is your confidence in the chosen classification \
(not the probability of AI authorship).
"""

_USER_PROMPT_TEMPLATE = """\
Analyze the following text and classify its origin:

---
{text}
---
"""

# ---------------------------------------------------------------------------
# Stylometric normalization ranges
# ---------------------------------------------------------------------------
# These define what raw metric values map to a score of 0.0 (human-like)
# and 1.0 (AI-like). Values outside the range are clamped.

# Sentence length variance: low variance → AI-like.
# Typical AI output: 2–30. Typical human prose: 50–300+.
_VAR_MIN = 0.0    # score 1.0  (perfectly uniform → strongly AI)
_VAR_MAX = 300.0  # score 0.0  (highly variable → strongly human)

# Type-token ratio: high diversity → human-like.
# TTR = unique_words / total_words.
# AI tends to cluster around 0.5–0.75; rich human writing often exceeds 0.75.
_TTR_MIN = 0.0    # score 1.0  (no diversity → AI/repetitive)
_TTR_MAX = 1.0    # score 0.0  (full diversity → human)

# Punctuation density: ratio of punctuation chars to all chars.
# AI text is conservative with punctuation; human informal text is not.
# Typical AI: 0.01–0.04. Rich human prose / dialogue: 0.05–0.15.
_PUNC_MIN = 0.0   # score 1.0  (no punctuation → strongly AI)
_PUNC_MAX = 0.08  # score 0.0  (dense punctuation → human)


class DetectionService:
    """
    Produces raw signal scores for a submitted text.

    Call run_llm_signal() and run_stylometric_signal() independently;
    their outputs are passed to ConfidenceService for combination.
    """

    def __init__(self, groq_api_key: str = ""):
        self._groq_api_key = groq_api_key

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def run_llm_signal(self, text: str) -> dict:
        """
        Call the Groq LLM to classify the text as human, AI, or uncertain.

        Returns:
            {
                "score":          float,  # 0.0 (human) → 1.0 (AI)
                "classification": str,   # "likely_human" | "likely_ai" | "uncertain"
                "confidence":     float, # model's confidence in its own classification
                "reasoning":      str,   # model's plain-language explanation
                "error":          str | None  # set if the API call failed
            }
        """
        if not self._groq_api_key or self._groq_api_key == "your-groq-api-key-here":
            print("[DetectionService] GROQ_API_KEY is missing or is still the placeholder value.")
            return self._llm_fallback("GROQ_API_KEY is not configured.")

        try:
            client = Groq(api_key=self._groq_api_key)

            response = client.chat.completions.create(
                model=_MODEL,
                temperature=_TEMPERATURE,
                timeout=_TIMEOUT,
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": _SYSTEM_PROMPT},
                    {"role": "user",   "content": _USER_PROMPT_TEMPLATE.format(text=text)},
                ],
            )

            raw_content = response.choices[0].message.content
            data = json.loads(raw_content)

            classification = data.get("classification", "uncertain")
            model_confidence = float(data.get("confidence", 0.5))
            reasoning = data.get("reasoning", "")

            # Convert (classification, model_confidence) → an AI-probability score.
            # The model returns its confidence in its OWN label. We convert
            # that into a [0,1] score where 1.0 = definitely AI.
            score = self._classification_to_score(classification, model_confidence)

            return {
                "score":          round(score, 4),
                "classification": classification,
                "confidence":     round(model_confidence, 4),
                "reasoning":      reasoning,
                "error":          None,
            }

        except json.JSONDecodeError as exc:
            print(f"[DetectionService] Groq response parse error: {exc}")
            return self._llm_fallback(f"Model returned non-JSON output: {exc}")
        except Exception as exc:
            # Catches network errors, auth errors, timeouts, etc.
            print(f"[DetectionService] Groq API call failed: {exc}")
            return self._llm_fallback(f"Groq API error: {exc}")

    def run_stylometric_signal(self, text: str) -> dict:
        """
        Compute four stylometric metrics and combine three into a score.

        Average sentence length is computed and returned for transparency
        but is NOT included in the weighted combination score because it
        overlaps with sentence-length variance and adds instability for
        short texts.

        Returns:
            {
                "score":      float,   # weighted combination, 0.0–1.0
                "components": {
                    "sentence_length_variance": {"raw": float, "score": float},
                    "average_sentence_length":  {"raw": float, "score": None},
                    "type_token_ratio":         {"raw": float, "score": float},
                    "punctuation_density":      {"raw": float, "score": float},
                }
            }
        """
        sentences  = self._split_sentences(text)
        words      = self._tokenize_words(text)
        all_chars  = text  # include spaces and punctuation

        # ---- Metric 1: Sentence Length Variance ---------------------------
        # Measures how uniform sentence lengths are across the passage.
        # AI writing tends to produce sentences of similar length because the
        # model optimises for coherent, balanced output. Human writing varies
        # more naturally — short punches, long elaborations.
        # Low variance → AI-like (score near 1.0).
        sentence_word_counts = [len(s.split()) for s in sentences if s.strip()]
        if len(sentence_word_counts) >= 2:
            mean = sum(sentence_word_counts) / len(sentence_word_counts)
            variance = sum((c - mean) ** 2 for c in sentence_word_counts) / len(sentence_word_counts)
        else:
            # Not enough sentences for a meaningful variance; use 0 (neutral).
            variance = 0.0

        slv_score = self._normalize_inverted(variance, _VAR_MIN, _VAR_MAX)

        # ---- Metric 2: Average Sentence Length ----------------------------
        # Informational only. AI writing often produces moderate-length
        # sentences (15–25 words). Very short (<8 words) or very long (>40
        # words) sentences are more characteristic of human writing styles.
        # Not included in the combined score — reported for transparency.
        avg_sentence_length = (
            sum(sentence_word_counts) / len(sentence_word_counts)
            if sentence_word_counts else 0.0
        )

        # ---- Metric 3: Type-Token Ratio (TTR) ----------------------------
        # TTR = unique word types / total word tokens.
        # Measures vocabulary diversity. Human writers — especially experts
        # or expressive writers — use a wider variety of words. AI writing
        # clusters around a moderate TTR, avoiding both extreme repetition
        # and unusually rare vocabulary.
        # Higher TTR → more human (score near 0.0).
        # NOTE: TTR shrinks naturally with text length. Scores for very short
        # texts (<50 words) are less reliable and should be interpreted
        # cautiously. This limitation is documented in planning.md.
        if words:
            unique_words = set(w.lower() for w in words)
            ttr = len(unique_words) / len(words)
        else:
            ttr = 0.5  # neutral fallback for empty text

        ttr_score = self._normalize_inverted(ttr, _TTR_MIN, _TTR_MAX)

        # ---- Metric 4: Punctuation Density --------------------------------
        # Ratio of punctuation characters to total characters.
        # AI writing is conventionally punctuated — it rarely uses
        # em-dashes for drama, ellipses for trailing thought, or exclamation
        # marks outside formal contexts. Human informal writing, narrative
        # prose, and dialogue are typically more punctuation-rich.
        # Lower density → AI-like (score near 1.0).
        if all_chars:
            punc_chars = sum(1 for ch in all_chars if ch in string.punctuation)
            punc_density = punc_chars / len(all_chars)
        else:
            punc_density = 0.0

        punc_score = self._normalize_inverted(punc_density, _PUNC_MIN, _PUNC_MAX)

        # ---- Combined stylometric score -----------------------------------
        # Weights from planning.md:
        #   sentence_length_variance  0.40  (most consistent predictor)
        #   type_token_ratio          0.35
        #   punctuation_density       0.25  (most genre-sensitive)
        combined = (
            slv_score  * 0.40 +
            ttr_score  * 0.35 +
            punc_score * 0.25
        )

        return {
            "score": round(combined, 4),
            "components": {
                "sentence_length_variance": {
                    "raw":   round(variance, 4),
                    "score": round(slv_score, 4),
                },
                "average_sentence_length": {
                    "raw":   round(avg_sentence_length, 4),
                    "score": None,  # informational — not part of combined score
                },
                "type_token_ratio": {
                    "raw":   round(ttr, 4),
                    "score": round(ttr_score, 4),
                },
                "punctuation_density": {
                    "raw":   round(punc_density, 6),
                    "score": round(punc_score, 4),
                },
            },
        }

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _classification_to_score(classification: str, model_confidence: float) -> float:
        """
        Convert the LLM's (classification, confidence) pair into a single
        AI-probability score on [0.0, 1.0].

        The model's 'confidence' is its confidence in its OWN label, not a
        direct AI-probability. We therefore invert it for "likely_human".

        Examples:
          ("likely_ai",    0.85) → 0.85   (high AI probability)
          ("likely_human", 0.90) → 0.10   (low AI probability)
          ("uncertain",    0.60) → 0.50   (always returns 0.50)
        """
        if classification == "likely_ai":
            return min(1.0, max(0.0, model_confidence))
        elif classification == "likely_human":
            return min(1.0, max(0.0, 1.0 - model_confidence))
        else:
            # "uncertain" — score sits at the midpoint regardless of confidence.
            return 0.50

    @staticmethod
    def _normalize_inverted(value: float, low: float, high: float) -> float:
        """
        Map a raw metric value to [0.0, 1.0] where:
          value ≤ low  → 1.0   (most AI-like end)
          value ≥ high → 0.0   (most human-like end)

        This is used for metrics where LOW values indicate AI authorship
        (variance, TTR, punctuation density).
        """
        if high == low:
            return 0.5
        ratio = (value - low) / (high - low)
        return round(1.0 - min(1.0, max(0.0, ratio)), 4)

    @staticmethod
    def _split_sentences(text: str) -> list[str]:
        """
        Split text into sentences on '.', '!', and '?' boundaries.
        Strips whitespace and discards empty segments.
        """
        parts = re.split(r"[.!?]+", text)
        return [p.strip() for p in parts if p.strip()]

    @staticmethod
    def _tokenize_words(text: str) -> list[str]:
        """
        Extract alphabetic word tokens from text (lowercase).
        Strips punctuation and numeric tokens.
        """
        return re.findall(r"[a-zA-Z]+", text)

    @staticmethod
    def _llm_fallback(reason: str) -> dict:
        """
        Return a safe neutral result when the Groq API call fails.

        Score 0.5 places the result in the "uncertain" band so the system
        does not falsely label content as AI when the signal is unavailable.
        The error field is surfaced in the API response so the caller knows
        the LLM signal did not run successfully.
        """
        return {
            "score":          0.5,
            "classification": "uncertain",
            "confidence":     0.5,
            "reasoning":      "LLM signal unavailable — using neutral fallback.",
            "error":          reason,
        }
